# Generated by Django 4.1.1 on 2022-10-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Card number')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('grant_date', models.DateField(auto_now_add=True, verbose_name='Fecha de otorgamiento')),
                ('expiry_date', models.DateField(verbose_name='Fecha de expiracion')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account id')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cardprovider', to_field='provider', verbose_name='Card provider')),
                ('type_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.typecard', to_field='type', verbose_name='Type card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'card',
                'managed': True,
            },
        ),
    ]
