# Generated by Django 4.1.1 on 2022-10-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cardprovider', verbose_name='Card provider'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.typecard', verbose_name='Type card'),
        ),
    ]
