# Generated by Django 4.1.1 on 2022-10-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_iban'),
        ('employee', '0003_employee_currently_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('PER', 'PERSONAL LOAN'), ('MRT', 'MORTGAGE'), ('STD', 'STUDENT LOAN'), ('AUT', 'AUTO LOAN'), ('PDY', 'PAYDAY LOAN'), ('PWN', 'PAWN SHOP LOAN'), ('SML', 'SMALL BUSINESS LOAN')], default='PER', max_length=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('granter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loan',
                'managed': True,
            },
        ),
    ]
