# Generated by Django 4.0.6 on 2022-10-04 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('address', '0003_alter_country_code_alter_state_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='Name')),
                ('employee_surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('employee_hire_date', models.DateField(verbose_name='Hire date')),
                ('employee_dni', models.IntegerField(verbose_name='DNI')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Address')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
