# Generated by Django 4.1.1 on 2022-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
