# Generated by Django 4.1.1 on 2022-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_employee_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currently_working',
            field=models.BooleanField(default=True),
        ),
    ]
