# Generated by Django 4.1.1 on 2022-09-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City name')),
            ],
            options={
                'verbose_name': 'City',
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, verbose_name='Country name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Country',
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, verbose_name='State name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'State',
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('address_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street name')),
                ('address_number', models.IntegerField(blank=True, null=True, verbose_name='Street number')),
                ('address_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='City')),
                ('address_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country')),
                ('address_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'address',
                'db_table': 'address',
                'managed': True,
            },
        ),
    ]
