# Generated by Django 4.1.1 on 2022-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, verbose_name='State name'),
        ),
    ]
