# Generated by Django 4.1.1 on 2022-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Country name'),
        ),
    ]
