# Generated by Django 4.1.1 on 2022-10-06 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=15, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Name')),
                ('customer_surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('customer_dni', models.IntegerField(verbose_name='DNI')),
                ('customer_dob', models.DateField(verbose_name='Hire date')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Address')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='Branch')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertype', verbose_name='Customer type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
