# Generated by Django 4.1.1 on 2022-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='customer_type',
            field=models.CharField(max_length=15, unique=True, verbose_name='Type'),
        ),
    ]
