# Generated by Django 4.1.1 on 2022-10-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customertype_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True, verbose_name='Type')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='Balance')),
                ('iban', models.CharField(editable=False, max_length=10, verbose_name='IBAN.\n                            Let it blank to generate it automatically')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.typeaccount', to_field='code', verbose_name='Account type')),
            ],
            options={
                'db_table': 'cuenta',
                'managed': True,
            },
        ),
    ]
