# Generated by Django 4.1.1 on 2022-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(editable=False, max_length=10, verbose_name='IBAN.'),
        ),
    ]
