# Generated by Django 4.1.1 on 2022-10-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('branch_number', models.IntegerField(unique=True, verbose_name='Branch number')),
                ('branch_name', models.CharField(max_length=50, unique=True, verbose_name='Branch name')),
                ('branch_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'db_table': 'branch',
                'managed': True,
            },
        ),
    ]
